spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtutorial?serverTimezone=Asia/Seoul
    username: root
    password: rlawnsdn6!

  jpa:
    show-sql: true
    ddl-auto: none